### PR TITLE
Attempting to make recommended movies display

### PR DESCRIPTION
**Pull request by Nramanan6**
Even after going through the edit profile activity, it gives me a null profile when I try to access the major of the current user.

### CODE REVIEW

**Comment by Nramanan6** [comment]
This branch also contains code for moving the responsibility of maintaining reviews to the movie rather than the movie manager. More efficient to search for ratings this way.

**Comment by jedyang97** [comment]
Well after a look at you code I think the problem is probably that the `sessionUser` field of `SessionState` is not properly maintained. If you look at the code of `SessionState`, when the app launches, it pulls username, password and userLevel from `SharedPreference` and then construct a new `User` object with these information. This means that every time the app launches, `profile` of `sessionUser` will be left blank.

And also take a look at the `updateUser()` method in `UserManager` class, it only persist the update to the database via DAOs, but it never update `sessionUser` in `SessionState`. That's why you said even after going through the profile page, the `profile` field still remains null.

**Comment by jedyang97** [comment]
Solutions:

For the first problem, you can probably change the code in `SessionState` from constructing a new `User` object to using DAOs to pull User information from the database.

For the second problem, just also update the `sessionUser` in `updateUser()`

**Comment by jedyang97** [comment]
[These code](https://github.com/YourTeamName/buzz-movie-selector/blob/nikhil/recommendationBackend/app/src/main/java/edu/gatech/buzzmovieselector/controller/activity/RecommendedMoviesActivity.java#L35-L48) should go under `MovieManager` (create a method in the facade and implement it in the manager). We should obey the MVC design pattern.

**Pull request merged**
