### PR TITLE
Nikhil/login handler

### PR DESCRIPTION
**Pull request by Nramanan6**
The registration now adds a user's name and password to the current list so they are able to login

### CODE REVIEW

**Comment by jedyang97** [comment]
Thanks, Nikhil! This is looking good. One thing: we are using the MVC design pattern, which means we want to decouple the logic of controllers and models as much as possible. Specifically, I think it would be better if methods like `usernameExists` and `registerUser` are moved into `UserManager`. Besides, there are a lot of confusing naming convention in the sample code Bob gave us. Like use `name` instead of `username`. I am going to fix that and the MVC staff. Anyway, it's good work!

**Comment by jedyang97** [comment]
Take a look at this commit. @Nramanan6

**Comment by Nramanan6** [comment]
For the method locations to follow MVC, I agree. I was only writing the bodies of the methods that someone had already inserted into the activity classes, and I think this new structure is better.
I also agree with your suggestion for the variable names.
If I'm not mistaken, the UserManager class still needs a checkUserExists() method, which I will get to next.

**Comment by Nramanan6** [comment]
Never mind, this is taken care of in the findUserById line. Looks like everything is good to go

**Comment by jedyang97** [comment]
LGTM👍(looks good to me)

**Comment by Nramanan6** [comment]
I also added a constructor for an admin account and took away the setAdmin() function - if we need it we can implement later but it seems to me that admin accounts will be registered on startup of the app and not change, which removes the need for a setAdmin() method

**Comment by jedyang97** [comment]
Make sense👍. Also, it would be better if you could change the parameter `u`, `p` and `a` to username, password and admin, which is more intuitive and convenient to use

**Comment by Nramanan6** [comment]
will do

**Comment by jedyang97** [comment]
I resolved conflicts in this branch with `develop`. After the merge, we should all pull from develop and resolve conflicts to prevent conflicts to "grow"

**Pull request merged**
